# Generated by Django 4.0.6 on 2022-08-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='foodend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.TextField()),
                ('price', models.IntegerField()),
                ('score', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('location', models.TextField()),
                ('category', models.TextField()),
            ],
            options={
                'db_table': 'foodend',
            },
        ),
        migrations.CreateModel(
            name='koreafood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.TextField()),
                ('price', models.IntegerField()),
                ('score', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('location', models.TextField()),
                ('category', models.TextField()),
            ],
            options={
                'db_table': 'koreafood',
            },
        ),
    ]
