# Generated by Django 4.0.6 on 2022-08-20 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_foodend_koreafood'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='koreafood',
            new_name='foodends',
        ),
        migrations.RenameModel(
            old_name='foodend',
            new_name='koreafoods',
        ),
        migrations.AlterModelTable(
            name='foodends',
            table='foodends',
        ),
        migrations.AlterModelTable(
            name='koreafoods',
            table='koreafoods',
        ),
    ]
